# Project-wide Gradle settings.

# JVM configuration
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true

# Kotlin
kotlin.code.style=official

# Resource namespacing
android.nonTransitiveRClass=true

# Improve dependency-model import performance
android.dependency.excludeLibraryComponentsFromConstraints=true